# Generated by Django 5.1.3 on 2024-12-22 12:45

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertising',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='advertising',
            name='expiration_date',
            field=models.DateTimeField(default=news.models.default_expiration_date),
        ),
    ]
